FROM golang:1.23.6 AS builder

WORKDIR /home/go/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 \
  GOOS=linux \
  GOARCH=amd64 \
  go build -ldflags="-w -s" -o app ./cmd/app/main.go

FROM scratch

WORKDIR /home/go/app

COPY --from=builder /home/go/app/app .
COPY --from=builder /home/go/app/.env .

ENTRYPOINT ["./app"]
