FROM node:22-alpine3.18 AS builder

RUN apk add --no-cache \
  openssl1.1-compat gcompat

WORKDIR /home/node/app

COPY package*.json ./
RUN npm install --omit=dev
COPY . .
RUN npx prisma generate
RUN npm run build

CMD ["sh", "-c", "npm run migration:dev && npm run start:dev & npm run start:dev -- --entryFile ./cmd/kafka.cmd.js"]
