FROM node:22-slim

RUN apt update && \
  apt install procps -y

WORKDIR /home/node/app

COPY . .

RUN npm install && \
  npm run prisma:generate && \
  npm run build

CMD ["sh", "-c", "node dist/main & node dist/cmd/kafka.cmd"]
