services:
  nestjs:
    build:
      context: .
      # dockerfile: Dockerfile.prod
      dockerfile: Dockerfile.local
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    networks:
      - go-gateway-api_default
    depends_on:
      nestjs-anti-fraud-db:
        condition: service_healthy

  nestjs-anti-fraud-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - 5433:5432
    networks:
      - go-gateway-api_default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_nestjs_anti_fraud:/var/lib/postgresql/data

volumes:
  postgres_data_nestjs_anti_fraud:

networks:
  go-gateway-api_default:
    external: true
