services:
  next-frontend:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/web/app
